SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[USP_SSF_AccountsFF] AS
BEGIN
SELECT [﻿ID]
     , ISDELETED
     , MASTERRECORDID
     , NAME
     , TYPE
     , RECORDTYPEID
     , PARENTID
     , BILLINGSTREET
     , BILLINGCITY
     , BILLINGSTATE
     , BILLINGPOSTALCODE
     , BILLINGCOUNTRY
     , BILLINGSTATECODE
     , BILLINGCOUNTRYCODE
     , BILLINGLATITUDE
     , BILLINGLONGITUDE
     , BILLINGGEOCODEACCURACY
     , BILLINGADDRESS
     , PHONE
     , FAX
     , ACCOUNTNUMBER
     , WEBSITE
     , PHOTOURL
     , INDUSTRY
     , ANNUALREVENUE
     , NUMBEROFEMPLOYEES
     , OWNERSHIP
     , TICKERSYMBOL
     , DESCRIPTION
     , CURRENCYISOCODE
     , OWNERID
     , CREATEDDATE
     , CREATEDBYID
     , LASTMODIFIEDDATE
     , LASTMODIFIEDBYID
     , SYSTEMMODSTAMP
     , LASTACTIVITYDATE
     , LASTVIEWEDDATE
     , LASTREFERENCEDDATE
     , ISPARTNER
     , ISCUSTOMERPORTAL
     , JIGSAW
     , JIGSAWCOMPANYID
     , ACCOUNTSOURCE
     , SICDESC
     , SUPPORT_PIN_CODE__C
     , SUPPORT_LEVEL_ESBU__C
     , ACCOUNT_NUMBER__C
     , ACCOUNT_PRIORITY__C
     , ACCOUNT_TYPE__C
     , APPROVED_AGENT__C
     , CCBU_SUPPORT_LEVEL__C
     , COMPANY_SIZE__C
     , CREDIT_LIMIT__C
     , CUSTOMER_PHASE_COMMERCIAL_DATE__C
     , CUSTOMER_PHASE_SETUP_DATE__C
     , CUSTOMER_PHASE_TRIAL_DATE__C
     , CUSTOMER_PHASE__C
     , CUSTOMER_REFERENCE_ID__C
     , DEFAULT_PRICE_BOOK__C
     , ENABLE_BANDWIDTH_THROTTLING__C
     , ENTERPRISE__C
     , ZUORA__ACTIVE__C
     , BILLING_COUNTRY_CODE
     , BILLING_STATE_NAME
     , BILLING_STATE_CODE
     , RED_Gate_ID FROM dbo.Account_FF
END

GO
